import numpy as np
from nomad.datamodel.data import EntryData
from nomad.datamodel.metainfo.annotations import (
    ELNAnnotation,
    ELNComponentEnum,
    SectionProperties,
)
from nomad.datamodel.metainfo.basesections import (
    CompositeSystemReference,
)
from nomad.metainfo import (
    Datetime,
    MEnum,
    Quantity,
    SchemaPackage,
    Section,
    SubSection,
)
from nomad_material_processing.general import (
    CrystallineSubstrate,
    Geometry,
    SubstrateReference,
    ThinFilm,
    ThinFilmStack,
    ThinFilmStackReference,
)
from structlog.stdlib import (
    BoundLogger,
)

from pdi_nomad_plugin.general.schema import (
    PDIMBECategory,
    SystemPDI,
)
from pdi_nomad_plugin.utils import (
    create_archive,
    get_hash_ref,
)

m_package = SchemaPackage()

ELEMENT_SYMBOLS = (
    'H',
    'He',
    'Li',
    'Be',
    'B',
    'C',
    'N',
    'O',
    'F',
    'Ne',
    'Na',
    'Mg',
    'Al',
    'Si',
    'P',
    'S',
    'Cl',
    'Ar',
    'K',
    'Ca',
    'Sc',
    'Ti',
    'V',
    'Cr',
    'Mn',
    'Fe',
    'Co',
    'Ni',
    'Cu',
    'Zn',
    'Ga',
    'Ge',
    'As',
    'Se',
    'Br',
    'Kr',
    'Rb',
    'Sr',
    'Y',
    'Zr',
    'Nb',
    'Mo',
    'Tc',
    'Ru',
    'Rh',
    'Pd',
    'Ag',
    'Cd',
    'In',
    'Sn',
    'Sb',
    'Te',
    'I',
    'Xe',
    'Cs',
    'Ba',
    'La',
    'Ce',
    'Pr',
    'Nd',
    'Pm',
    'Sm',
    'Eu',
    'Gd',
    'Tb',
    'Dy',
    'Ho',
    'Er',
    'Tm',
    'Yb',
    'Lu',
    'Hf',
    'Ta',
    'W',
    'Re',
    'Os',
    'Ir',
    'Pt',
    'Au',
    'Hg',
    'Tl',
    'Pb',
    'Bi',
    'Po',
    'At',
    'Rn',
    'Fr',
    'Ra',
    'Ac',
    'Th',
    'Pa',
    'U',
    'Np',
    'Pu',
    'Am',
    'Cm',
    'Bk',
    'Cf',
    'Es',
    'Fm',
    'Md',
    'No',
    'Lr',
    'Rf',
    'Db',
    'Sg',
    'Bh',
    'Hs',
    'Mt',
    'Ds',
    'Rg',
    'Cn',
    'Nh',
    'Fl',
    'Mc',
    'Lv',
    'Ts',
    'Og',
)

MBE_DOPANT_ELEMENTS = (
    'Ba',
    'Ge',
    'Sn',
    'Si',
    'La',
    'In',
    'Sb',
    'Al',
)


class SubstrateMbe(SystemPDI, CrystallineSubstrate, EntryData):
    """
    Class autogenerated from yaml schema.
    """

    m_def = Section(
        label_quantity='lab_id',
        categories=[PDIMBECategory],
        label='Substrate',
        a_eln=ELNAnnotation(
            properties=SectionProperties(
                order=[
                    'name',
                    'tags',
                    'delivery_date',
                    'as_delivered',
                    'fresh',
                    'processed',
                    'grown',
                    'datetime',
                    'supplier',
                    'supplier_id',
                    'material_designation',
                    'crystal_id',
                    'charge_id',
                    'polishing',
                    'offcut_angle',
                    'offcut_direction',
                    'lab_id',
                    'epi_ready',
                    'substrate_image',
                    'information_sheet',
                    'description',
                ],
            ),
            lane_width='600px',
        ),
    )
    tags = Quantity(
        type=str,
        shape=['*'],
        description='Searchable tags for this entry. Use Explore tab for searching.',
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
        ),
    )
    delivery_date = Quantity(
        type=Datetime,
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.DateEditQuantity,
        ),
    )
    material_designation = Quantity(
        type=str,
        description=(
            'Human-readable substrate material designation, '
            'e.g. SrTiO3, GdScO3, YSZ, or BaSnO3.'
        ),
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
            label='Material / Crystal designation',
        ),
    )

    crystal_id = Quantity(
        type=str,
        description=(
            'The ID of the crystal from which the current batch was cut, '
            'given by the manufacturer.'
        ),
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
        ),
        label='Crystal ID',
    )
    charge_id = Quantity(
        type=str,
        description=(
            'The ID of the charge, or polishing batch, given by the manufacturer.'
        ),
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
            label='Charge ID',
        ),
    )
    polishing = Quantity(
        type=MEnum(
            'Single-side',
            'Double-side',
            'other',
            'none',
        ),
        description='The polishing applied to the material.',
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.EnumEditQuantity,
        ),
    )
    surface_orientation_label = Quantity(
        type=str,
        description=(
            'Compact surface orientation used for substrate catalogue '
            'display and search.'
        ),
    )
    offcut_angle = Quantity(
        type=float,
        unit='degree',
        description='Nominal substrate offcut angle.',
        a_eln=ELNAnnotation(
            component='NumberEditQuantity',
            label='Offcut angle',
        ),
    )
    offcut_direction = Quantity(
        type=str,
        description='Crystallographic direction towards which the substrate is offcut.',
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
            label='Offcut direction',
        ),
    )
    offcut_label = Quantity(
        type=str,
        description='Compact offcut description used for catalogue display and search.',
    )
    description = Quantity(
        type=str,
        description='description',
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
            label='Notes',
        ),
    )
    parent_sample = SubSection(
        description="""
        The parent sample from which the current substrate was cut.
        """,
        section_def=SubstrateReference,
    )

    def normalize(self, archive, logger):
        super().normalize(archive, logger)

        logger.info('Running SubstrateMbe normalization')

        # Initialize substrate status
        if self.as_delivered is None:
            self.as_delivered = True
        if self.fresh is None:
            self.fresh = False
        if self.processed is None:
            self.processed = False
        if self.grown is None:
            self.grown = False

        # Build compact orientation and offcut labels for catalogue search/display.
        if self.crystal_properties:
            surface_orientation = getattr(
                self.crystal_properties, 'surface_orientation', None
            )
            hkl = getattr(surface_orientation, 'hkl_reciprocal', None)
            if hkl:
                indices = [
                    getattr(hkl, 'h_index', None),
                    getattr(hkl, 'k_index', None),
                    getattr(hkl, 'l_index', None),
                ]
                if all(index is not None for index in indices):
                    formatted_indices = []
                    for index in indices:
                        value = float(index)
                        if value.is_integer():
                            formatted_indices.append(str(int(value)))
                        else:
                            formatted_indices.append(f'{value:g}')
                    self.surface_orientation_label = f'({"".join(formatted_indices)})'

        if self.offcut_angle is not None:
            angle = self.offcut_angle
            if hasattr(angle, 'magnitude'):
                angle = angle.magnitude
            self.offcut_label = f'{float(angle):g}Â°'
        else:
            self.offcut_label = None

        # -------------------------------------------------
        # Construct substrate ID if not explicitly given
        # -------------------------------------------------

        if (
            self.supplier_id is not None
            and self.crystal_id is not None
            and self.charge_id is not None
            and self.lab_id is None
        ):
            self.lab_id = f'{self.supplier_id}_{self.crystal_id}_{self.charge_id}'
        elif (
            self.supplier_id is not None
            and self.crystal_id is not None
            and self.charge_id is not None
            and self.lab_id is not None
        ):
            logger.warning(
                'Substrate ID already given; '
                'supplier_id, crystal_id, charge_id not used.'
            )
        elif (
            self.supplier_id is None
            and self.crystal_id is None
            and self.charge_id is None
            and self.lab_id is None
        ):
            logger.error(
                'Substrate ID expected but missing. '
                'Provide supplier_id, crystal_id, charge_id, or Substrate ID.'
            )

        # -------------------------------------------------
        # Initialize NOMAD results structure
        # -------------------------------------------------
        if archive.results is None:
            from nomad.datamodel.results import Results

            archive.results = Results()

        if archive.results.material is None:
            from nomad.datamodel.results import Material

            archive.results.material = Material()

        material = archive.results.material

        # -------------------------------------------------
        # Chemical formula (use existing NOMAD fields)
        # -------------------------------------------------
        formula = None

        if self.components:
            for component in self.components:
                if (
                    hasattr(component, 'pure_substance')
                    and component.pure_substance
                    and getattr(component.pure_substance, 'molecular_formula', None)
                ):
                    formula = component.pure_substance.molecular_formula
                    break

        if not formula and getattr(self, 'chemical_formula', None):
            formula = self.chemical_formula

        if formula:
            material.chemical_formula_descriptive = formula
            material.chemical_formula_hill = formula
            material.chemical_formula_reduced = formula
            material.material_name = formula

        # -------------------------------------------------
        # Structural properties
        # -------------------------------------------------
        material.structural_type = 'bulk'
        material.dimensionality = '3D'

        # -------------------------------------------------
        # Symmetry
        # -------------------------------------------------
        if self.crystal_properties:
            if material.symmetry is None:
                from nomad.datamodel.results import Symmetry

                material.symmetry = Symmetry()

            #  DEFINE THE MAP
            lattice_map = {
                'fcc': 'cF',
                'bcc': 'cI',
                'cubic': 'cP',
                'hexagonal': 'hP',
                'trigonal': 'hR',
                'rhombohedral': 'hR',
            }

            # ---- Bravais lattice  ----
            b_lattice_raw = getattr(self.crystal_properties, 'bravais_lattice', None)

            if b_lattice_raw is None:
                b_lattice_raw = getattr(
                    self.crystal_properties, 'bravais_lattices', None
                )

            if isinstance(b_lattice_raw, list) and len(b_lattice_raw) > 0:
                b_lattice_raw = b_lattice_raw[0]

            if b_lattice_raw:
                clean_raw = str(b_lattice_raw).strip()

                if clean_raw.lower() in lattice_map:
                    material.symmetry.bravais_lattice = lattice_map[clean_raw.lower()]
                    logger.info(
                        f'âœ“ Mapped lattice: {clean_raw} -> '
                        f'{lattice_map[clean_raw.lower()]}'
                    )

                elif (
                    clean_raw
                    in material.symmetry.m_def.quantities['bravais_lattice'].type
                ):
                    material.symmetry.bravais_lattice = clean_raw
                    logger.info(f'âœ“ Set lattice directly: {clean_raw}')
                else:
                    logger.warning(f'Ignoring invalid bravais_lattice: {clean_raw}')
            else:
                logger.warning(
                    'Still could not find bravais_lattice or bravais_lattices'
                )

            # ---- Crystal System ----
            if (
                material.symmetry.bravais_lattice
                and not material.symmetry.crystal_system
            ):
                lattice = material.symmetry.bravais_lattice
                pearson_first = lattice[0]  # First letter

                if lattice == 'hR':
                    material.symmetry.crystal_system = 'trigonal'
                    logger.info(
                        "âœ“ Inferred crystal_system 'trigonal' from lattice 'hR'"
                    )
                else:
                    # Standard lookup
                    system_lookup = {
                        'a': 'triclinic',
                        'm': 'monoclinic',
                        'o': 'orthorhombic',
                        't': 'tetragonal',
                        'h': 'hexagonal',
                        'c': 'cubic',
                    }
                    if pearson_first in system_lookup:
                        material.symmetry.crystal_system = system_lookup[pearson_first]
                        logger.info(
                            f'âœ“ Inferred crystal_system '
                            f"'{system_lookup[pearson_first]}' "
                            f"from lattice '{lattice}'"
                        )
        # -------------------------------------------------
        # Method
        # -------------------------------------------------
        # if archive.results.method is None:
        #     from nomad.datamodel.results import Method
        #     archive.results.method = Method()

        # archive.results.method.method_name = "bulk growth"

        logger.info('SubstrateMbe normalization completed')


class SubstrateBatchMbe(SubstrateMbe, EntryData):
    """
    Class autogenerated from yaml schema.
    """

    m_def = Section(
        label_quantity='lab_id',
        categories=[PDIMBECategory],
        label='Substrate Batch',
        a_eln=ELNAnnotation(
            properties=SectionProperties(
                order=[
                    'name',
                    'delivery_date',
                    'datetime',
                    'supplier',
                    'supplier_id',
                    'material_designation',
                    'crystal_id',
                    'charge_id',
                    'polishing',
                    'offcut_angle',
                    'offcut_direction',
                    'lab_id',
                    'number_of_substrates',
                    'epi_ready',
                    'substrate_image',
                    'information_sheet',
                    'description',
                ],
            ),
            lane_width='600px',
        ),
    )
    number_of_substrates = Quantity(
        type=int,
        description='The number of substrates in the batch.',
        a_eln=dict(component='NumberEditQuantity'),
    )
    trigger_create_substrate = Quantity(
        type=bool,
        description="""
        Create Substrate entries based on the current Substrate Batch entry and add
        references to then in `substrates` subsection.
        WARNING: If `substrates` is non-empty, the existing entries and references
        will be overwritten.
        """,
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.ActionEditQuantity,
            label='Create Substrates',
        ),
    )
    substrates = SubSection(
        description="""
        The substrates in the batch.
        """,
        section_def=CompositeSystemReference,
        repeats=True,
    )

    def normalize(self, archive, logger):
        from nomad.datamodel import EntryArchive, EntryMetadata

        super().normalize(archive, logger)
        filetype = 'yaml'

        # if (
        #     self.supplier_id is not None
        #     and self.crystal_id is not None
        #     and self.charge_id is not None
        #     and self.lab_id is None
        # ):
        #     self.lab_id = f'{self.supplier_id}_{self.crystal_id}_{self.charge_id}'
        # elif (
        #     self.supplier_id is not None
        #     and self.crystal_id is not None
        #     and self.charge_id is not None
        #     and self.lab_id is not None
        # ):
        #     logger.warning(
        #         f"Error in SubstrateBatch: 'Substrate ID' is already given."
        #     )
        # elif (
        #     self.supplier_id is None
        #     and self.crystal_id is None
        #     and self.charge_id is None
        #     and self.lab_id is None
        # ):
        #     logger.error(
        #         f"Error in SubstrateBatch: 'Substrate ID' expected, "
        #         f"but None found.\n"
        #         f"Please provide 'supplier_id', 'crystal_id', 'charge_id' "
        #         f"and 'lab_id'."
        #     )

        if self.trigger_create_substrate:
            self.substrates = []
            if not self.number_of_substrates:
                logger.error(
                    "Error in SubstrateBatch: 'number_of_substrates' expected, "
                    'but None found.'
                )
            else:
                substrate_object = self.m_copy(deep=True)
                substrate_object.m_def = SubstrateMbe.m_def
                substrate_object.number_of_substrates = None
                for substrate_index in range(1, self.number_of_substrates + 1):
                    child_name = self.lab_id if self.lab_id else self.name
                    substrate_filename = (
                        f'{child_name}_{substrate_index}.Substrate.archive.{filetype}'
                    )
                    substrate_object.name = f'{child_name}_{substrate_index}'
                    substrate_object.lab_id = f'{child_name}_{substrate_index}'
                    substrate_archive = EntryArchive(
                        data=substrate_object,
                        m_context=archive.m_context,
                        metadata=EntryMetadata(upload_id=archive.m_context.upload_id),
                    )
                    if not archive.m_context.raw_path_exists(substrate_filename):
                        create_archive(
                            substrate_archive.m_to_dict(),
                            archive.m_context,
                            substrate_filename,
                            filetype,
                            logger,
                        )
                    self.substrates.append(
                        CompositeSystemReference(
                            name=substrate_object.name,
                            reference=get_hash_ref(
                                archive.m_context.upload_id, substrate_filename
                            ),
                        ),
                    )
            self.trigger_create_substrate = False


class ThinFilmMbe(SystemPDI, ThinFilm, EntryData):
    """
    Class autogenerated from yaml schema.
    """

    m_def = Section(
        label_quantity='lab_id',
        categories=[PDIMBECategory],
        label='ThinFilmMbe',
    )
    lab_id = Quantity(
        type=str,
        description='the Sample created in the current growth',
        a_tabular={'name': 'GrowthRun/Sample Name'},
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
            label='Grown Sample ID',
        ),
    )
    tags = Quantity(
        type=str,
        shape=['*'],
        description='Searchable tags for this entry. Use Explore tab for searching.',
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
        ),
    )
    chemical_formula = Quantity(
        type=str,
        description='Nominal chemical formula of this thin-film layer.',
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.StringEditQuantity,
            label='Composition',
        ),
    )
    dopant_element = Quantity(
        type=MEnum(*MBE_DOPANT_ELEMENTS),
        description='Chemical element used as dopant in this layer.',
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.EnumEditQuantity,
            label='Dopant element',
        ),
    )
    nominal_thickness = Quantity(
        type=np.float64,
        unit='meter',
        description='Nominal thickness of this thin-film layer.',
        a_eln=ELNAnnotation(
            component=ELNComponentEnum.NumberEditQuantity,
            label='Nominal thickness',
            defaultDisplayUnit='nanometer',
        ),
    )
    test_quantities = Quantity(
        type=str,
        description='Test quantity',
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
        ),
    )


class ThinFilmStackMbePDI(SystemPDI, ThinFilmStack, EntryData):
    """
    Class autogenerated from yaml schema.
    """

    m_def = Section(
        label_quantity='lab_id',
        categories=[PDIMBECategory],
        label='ThinFilmStackMbe',
    )
    lab_id = Quantity(
        type=str,
        description='the Sample created in the current growth',
        a_tabular={'name': 'GrowthRun/Sample Name'},
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
            label='Grown Sample ID',
        ),
    )
    tags = Quantity(
        type=str,
        shape=['*'],
        description='Searchable tags for this entry. Use Explore tab for searching.',
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
        ),
    )
    parent_sample = SubSection(
        description="""
        the parent sample of the current sample.
        """,
        section_def=ThinFilmStackReference,
    )
    geometry = SubSection(
        section_def=Geometry,
        description='Section containing the geometry of the thin film.',
    )


class ThinFilmStackMbeReference(ThinFilmStackReference):
    """
    A section used for referencing a Grown Sample.
    """

    lab_id = Quantity(
        type=str,
        description='the Sample created in the current growth',
        a_tabular={'name': 'GrowthRun/Sample Name'},
        a_eln=ELNAnnotation(
            component='StringEditQuantity',
            label='Grown Sample ID',
        ),
    )
    reference = Quantity(
        type=ThinFilmStackMbePDI,
        description='A reference to a NOMAD `ThinFilmStackMbe` entry.',
        a_eln=ELNAnnotation(
            component='ReferenceEditQuantity',
            label='ThinFilmStackMbe Reference',
        ),
    )

    def normalize(self, archive, logger: BoundLogger) -> None:
        """
        The normalizer for the `ThinFilmStackMbeReference` class.
        """
        super().normalize(archive, logger)


m_package.__init_metainfo__()
